import Device from '../context/EnvironmentContext/Device';

const devices: Device[] = [
  {
    type: 'hueLight',
    home: 'demo',
    key: 'demo-6',
    baseKey: 'lights.2',
    room: 'Kitchen',
    config: { name: 'Light 1' },
  },
  {
    type: 'hueLight',
    home: 'demo',
    key: 'demo-7',
    baseKey: 'lights.3',
    room: 'Kitchen',
    config: { name: 'Light 2' },
  },
  {
    type: 'button',
    home: 'demo',
    key: 'demo-8',
    baseKey: 'buttons.3',
    room: 'Kitchen',
    config: { name: 'On Switch' },
  },
  {
    type: 'button',
    home: 'demo',
    key: 'demo-9',
    baseKey: 'buttons.2',
    room: 'Kitchen',
    config: { name: 'Off Switch' },
  },
  {
    type: 'motionSensor',
    home: 'demo',
    key: 'demo-10',
    baseKey: 'motionSensors.1',
    room: 'Kitchen',
    config: { name: 'Motion Sensor' },
  },
  {
    type: 'hueLight',
    home: 'demo',
    key: 'demo-1',
    baseKey: 'lights.0',
    room: 'Living Room',
    config: { name: 'Light 1' },
  },
  {
    type: 'hueLight',
    home: 'demo',
    key: 'demo-5',
    baseKey: 'lights.1',
    room: 'Living Room',
    config: { name: 'Light 2' },
  },
  {
    type: 'button',
    home: 'demo',
    key: 'demo-2',
    baseKey: 'buttons.0',
    room: 'Living Room',
    config: { name: 'On Switch' },
  },
  {
    type: 'button',
    home: 'demo',
    key: 'demo-3',
    baseKey: 'buttons.1',
    room: 'Living Room',
    config: { name: 'Off Switch' },
  },
  {
    type: 'motionSensor',
    home: 'demo',
    key: 'demo-4',
    baseKey: 'motionSensors.0',
    room: 'Living Room',
    config: { name: 'Motion Sensor' },
  },
];

export default devices;
