name: Publish

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}

      - name: Configure CI Git User
        run: |
          git config --global user.name '@morten-olsen'
          git config --global user.email 'morten-olsen@users.noreply.github.com'
          git remote set-url origin https://$GITHUB_ACTOR:$GITHUB_PAT@github.com/morten-olsen/iot
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Packages
        run: yarn install

      - name: Publish package
        run: "yarn lerna publish --prerelease --yes --message 'chore: release new versions %s'"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}


